CREATE TABLE SA.PERSON
(
  ID                 VARCHAR  (5)    NOT NULL,
  FIRST_NAME         VARCHAR  (40)   NOT NULL,
  LAST_NAME          VARCHAR  (40)   NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE SA.ACCOUNT
(
  ID                 VARCHAR  (5)    NOT NULL,
  NAME               VARCHAR  (10)   NOT NULL,
  PRIMARY KEY (ID)
);