/*
 * Copyright 2006 Niclas Hedhman.
 *
 * Licensed  under the  Apache License,  Version 2.0  (the "License");
 * you may not use  this file  except in  compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed  under the  License is distributed on an "AS IS" BASIS,
 * WITHOUT  WARRANTIES OR CONDITIONS  OF ANY KIND, either  express  or
 * implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License. 
 */
package org.qi4j.query;

import java.lang.reflect.InvocationHandler;
import java.lang.reflect.Proxy;
import java.util.ArrayList;
import org.qi4j.query.value.MethodCallExpression;

public final class QueryBuilderImpl<R>
    implements QueryBuilder<R>
{
    private Class resultType;
    private Queryable queryable;
    private ArrayList<BooleanExpression> where;
    private ArrayList<OrderBy> orderBy;
    private int firstResult = -1;
    private int maxResults = -1;

    public QueryBuilderImpl( Class<R> resultType, Queryable queryable )
    {
        this.resultType = resultType;
        this.queryable = queryable;
        where = new ArrayList<BooleanExpression>();
        orderBy = new ArrayList<OrderBy>();
    }

    public <K> K parameter( Class<K> mixinType )
    {
        ClassLoader loader = QueryBuilderImpl.class.getClassLoader();
        Class[] intfaces = new Class[]{ mixinType };
        InvocationHandler handler = new InterfaceInvocationHandler();
        return (K) Proxy.newProxyInstance( loader, intfaces, handler );
    }

    public QueryBuilder<R> where( BooleanExpression... expressions )
    {
        for( BooleanExpression expr : expressions )
        {
            where.add( expr );
        }
        return this;
    }

    public QueryBuilder<R> orderBy( Object property )
    {
        MethodCallExpression expression = (MethodCallExpression) QueryStack.popExpression();
        OrderBy by = new OrderBy( expression, OrderBy.Order.ASCENDING );
        orderBy.add( by );
        return this;
    }

    public QueryBuilder<R> orderBy( Object property, OrderBy.Order orderBy )
    {
        MethodCallExpression expression = (MethodCallExpression) QueryStack.popExpression();
        OrderBy by = new OrderBy( expression, orderBy );
        this.orderBy.add( by );
        return this;
    }

    public QueryBuilder<R> setFirstResult( int firstResult )
    {
        this.firstResult = firstResult;
        return this;
    }

    public QueryBuilder<R> setMaxResults( int maxResults )
    {
        this.maxResults = maxResults;
        return this;
    }

    public <K> QueryBuilder<K> resultSet( K property )
    {
        return null;  //TODO: Autogenerated
    }

    public <K> QueryBuilder<K> resultList( K property )
    {
        return new QueryBuilderImpl<K>( (Class<K>) property.getClass(), new QueryableIterable( newQuery() ) );
    }

    public Query<R> newQuery()
    {
        return new QueryImpl<R>( resultType, where, orderBy, firstResult, maxResults, queryable );
    }

}
